### ISSUE TITLE
Some object types has no trail

### ISSUE THREAD

**Issue by stratus9** [PolaricServer/aprsd#30]
Objects like balloons (\O) or motocycles (/<) or jogger (/[) have no trail on the map.

**Comment by ohanssen** [comment]
Thanks for your feedback. APRS objects have no trail. Most objects are not moving so the focus was on active APRS stations (trackers). I will keep this issue open and try to add trails to moving objects as well..

**Comment by ohanssen** [comment]
I believe this works now..
