### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by JeffHochberg** [PolaricServer/aprsd#31]
Hello,

I've been looking around on the aprs.no site as well as a third-party site (APRS Box) and I'm struggling to find documentation that has more "real world" examples of how to configure Polaric APRS and the corresponding web server.

One very basic thing I haven't been able to find is how to reconfigure the language for the web interface to English. What am I missing here?

Is there any other documentation other than what's on aprs.no and Github that you can share?

Thank you!

**Comment by ohanssen** [comment]
Thanks for your feedback. I guess you have seen the wiki pages: http://aprs.no/polaricserver

I agree that documentation could be better. There are some descriptions on how to install and do basic configuration, though more examples and details would be useful. 

Since this is mostly a one-man project it is vulnerable - Any help would be appreciated. Also pointing out what should be improved is useful.

**Comment by cyberjew** [comment]
I’d be happy to help! Maybe we can spend some time together getting a US
based instance up and running, then I can help with documentation of it?

**Comment by ohanssen** [comment]
Sure, I'll be happy to help. I may be somewhat busy this week, but feel free to contact me and I see what I can du..

**Comment by cyberjew** [comment]
I’m actually out of town on business this week and next. We can start
planning for the week of 2-Sept if that works for you.

**Comment by cyberjew** [comment]
Oyvind,

If you're still interested, please feel free to reach out to me directly
and we can set up some time to review localization of PolaricServer.

As I mentioned, I'd be happy to set up an instance of it so you can get me
pointed in the right direction. Then I can work on it independently and
report back to you with findings.

You can reach me via jeff [at] w4jew [dot] com. I look forward to hearing
from you soon!

-JeffH

Jeff Hochberg
W4JEW
Atlanta, GA
