### ISSUE TITLE
not working on Rpi B+ v1.2

### ISSUE THREAD

**Issue by kalashnikov2** [PolaricServer/aprsd#39]
Hello
thank you for developing this program.

I tried to install on a RPI B+ v1.2

but it was not possible, because of this error, I suppose it is too old for the required software.

`Error occurred during initialization of VM
Server VM is only supported on ARMv7+ VFP
`
raw output apt install  . .   https://pastebin.com/raw/7r4EUW9A

the RPI B+ v1.2   uname result
`Linux raspberrypi-aprs 5.4.51+ #1333 Mon Aug 10 16:38:02 BST 2020 armv6l GNU/Linux
`

i will try on a RPI 3 B+

:D

**Comment by ohanssen** [comment]
Sorry for my late response. Yes. Java 9 or later (OpenJDK) will not run on older ARM.  I guess the easiest solution is to use a RPI2, RPI3 or RPI4. Now, it is just a question of building the OpenJDK for the target platform, so it is possible. It also seems like some builds exist out there. For example Zulu OpenJDK.
