### ISSUE TITLE
Unable to install webapp2 via apt in Docker

### ISSUE THREAD

**Issue by martinhpedersen** [PolaricServer/aprsd#42]
Hei Øyvind 🙂 

This bug seems to be related to commit b28d9088a17619ad741ef5a95bf08a04a16f3986. The commit message ("postinst fix") indicates that it fixes some other issue related to these files, but does not reference the actual change that required this "fix". I believe I'm experiencing another bug related to what b28d9088a17619ad741ef5a95bf08a04a16f3986 fixed.

The installation was working flawlessly with aprsd 2.6.2 and webapp2 1.5.1, so the issue seems to have been introduced in some release after those.

Here is the gist of my output when trying to install polaric-aprsd and polaric-webapp2:

```
Setting up polaric-webapp2 (1.6) ...
chown: cannot access '/var/lib/polaric/mapcache/*.db': No such file or directory
dpkg: error processing package polaric-webapp2 (--configure):
 installed polaric-webapp2 package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.28-10) ...
Errors were encountered while processing:
 polaric-webapp2
```

Any idea what's changed related to these files?

I have a feeling these (missing) files are generated after the first run of aprsd(?), and the installation of webapp2 is failing because it requires aprsd to be started on the system  prior to installation. Any way this can be fixed?

-----

Here is my Dockerfile, showing all commands executed:
```
FROM debian:stable-slim

# Add polaric-server apt repo
RUN apt-get update && apt-get -y install gnupg2 dirmngr
RUN gpg --keyserver pool.sks-keyservers.net --recv-keys 89E7229CFFD59B2F && gpg --export --armor 3E61003E24632585EB3DFE3D89E7229CFFD59B2F | apt-key add -
RUN echo "deb http://aprs.no/debian-rep binary-dev/" >> /etc/apt/sources.list && apt-get update

# Install Java (with hack for slim image)
RUN mkdir -p /usr/share/man/man1
RUN apt-get -y install default-jdk-headless

# Install polaric components
RUN apt-get -y install polaric-aprsd polaric-webapp2 polaric-ais-plugin
```

**Comment by ohanssen** [comment]
Hi, Martin, does it work now with the latest updates (webapp2 1.6.1 and 1.6.2)? Some issues regarding missing mapcache files were addressed there

**Comment by martinhpedersen** [comment]
Øyvind, sorry for the delayed response.

I haven't had time to test with the latest updates yet. I'll get back to you as soon as possible 🙂

**Comment by ohanssen** [comment]
I have created a new repository for Docker setup examples and added one working one for webapp2. Feel free to contribute. I am therefore closing this issue..
