### ISSUE TITLE
NullPointerException in TrackerPoint.saveToTrail

### ISSUE THREAD

**Issue by martinhpedersen** [PolaricServer/aprsd#43]
I'm suddenly seeing lots of NullPointerExceptions in the log. No changes in the setup, so I'm guessing this is due to some recent data in AIS feed that trigged this.

```
aprsd_1       | java.lang.NullPointerException
aprsd_1       | 	at no.polaric.aprsd.TrackerPoint.saveToTrail(TrackerPoint.java:182)
aprsd_1       | 	at no.polaric.ais.AisChannel.updatePos(AisChannel.java:106)
aprsd_1       | 	at no.polaric.ais.AisChannel.updatePosExtra(AisChannel.java:116)
aprsd_1       | 	at no.polaric.ais.AisChannel$1.accept(AisChannel.java:195)
aprsd_1       | 	at no.polaric.ais.AisChannel$1.accept(AisChannel.java:184)
aprsd_1       | 	at dk.dma.ais.reader.AisReader.distribute(AisReader.java:218)
aprsd_1       | 	at dk.dma.ais.reader.AisReader.readLoop(AisReader.java:200)
aprsd_1       | 	at dk.dma.ais.reader.AisTcpReader.run(AisTcpReader.java:113)
```
https://github.com/PolaricServer/aprsd/blob/0e1dbb2c2212d0b2459791b5e08779d73ac3ac70/src/TrackerPoint.java#L182

----

It might be unrelated, but the webapp2 frontend code started failing at the same time:

![Skjermbilde 2021-05-16 kl  11 39 38](https://user-images.githubusercontent.com/1265622/118393982-39474180-b642-11eb-888c-6f392eb0d131.png)
![Skjermbilde 2021-05-16 kl  11 39 25](https://user-images.githubusercontent.com/1265622/118393984-3c423200-b642-11eb-8add-4cefc3e2ad3b.png)

**Comment by martinhpedersen** [comment]
Running aprsd 2.6.2 and webapp2 1.5.1.

Clearing the data directory /var/lib/polaric seems to be a work-around, suggesting a bug in the persistence layer.

**Comment by ohanssen** [comment]
This nullpointer exception related to recording routes of traffix amongst APRS digipeaters so AIS is not relevant. It is not critical. I add a test if _db.getRoutes() is null in the next release.
