### ISSUE TITLE
Support for telemetry decoding

### ISSUE THREAD

**Issue by elafargue** [PolaricServer/aprsd#7]
Not so much an issue as an enhancement: it would be great to add support for telemetry packets in aprsd, so that telemetry stations can be displayed in the web app. I am planning to do experimental broadcasting of telemetry information my my base station, and would love to see those displayed on Polaric.

Great resource on APRS telemetry - very clear description: https://github.com/wb2osz/direwolf/blob/dev/doc/APRS-Telemetry-Toolkit.pdf

**Comment by ohanssen** [comment]
Basic telemetry support is now implemented. It is a start. Graphic presentation can be added later.
