### ISSUE TITLE
Packets never showing up on map

### ISSUE THREAD

**Issue by elafargue** [PolaricServer/aprsd#8]
Maybe linked to telemetry support? The reports below never end up on the Polaric Webapp map, though they are forwarded by aprsd (they show up on aprsdroid):

```
polaric APRS 03 nov 2015 01:12:09 [rf0] N8QH-9>APOT30,N6ZX-3*,WIDE1*,WIDE2-1:
direwolf APRS Nov 3 01:17:10 aprs direwolf: [0.4] N8QH-9>APOT30,N8QH-9,N6ZX-3,WIDE2*:<0x0a>$ULTW012F00F502A700772765000085A0000102390131041A000000CD<0x0d>
polaric APRS 03 nov 2015 01:17:10 [rf0] N8QH-9>APOT30,N8QH-9*,N6ZX-3*,WIDE2*:
direwolf APRS Nov 3 01:22:10 aprs direwolf: [0.4] N8QH-9>APOT30,N8QH-9,N6ZX-3,WIDE2*:<0x0a>$ULTW012900EF02A600772764000085A00001023B0131041F000000BE<0x0d>
polaric APRS 03 nov 2015 01:22:10 [rf0] N8QH-9>APOT30,N8QH-9*,N6ZX-3*,WIDE2*:
direwolf APRS Nov 3 01:27:08 aprs direwolf: [0.3] N8QH-9>APOT30,N6ZX-3,WIDE1*,WIDE2-1:<0x0a>$ULTW00D2001602A500772763FFFF85A00001023D013104240000008F<0x0d>
polaric APRS 03 nov 2015 01:27:09 [rf0] N8QH-9>APOT30,N6ZX-3*,WIDE1*,WIDE2-1:
direwolf APRS Nov 3 01:27:44 aprs direwolf: [0.3] N8QH-9>APOT30,N6ZX-3,WIDE1*,WIDE2-1:/012741h/;Qr(/QwDY st 13.1V 71F HDOP00.7 SATS16
polaric APRS 03 nov 2015 01:27:44 [rf0] N8QH-9>APOT30,N6ZX-3*,WIDE1*,WIDE2-1:/012741h/;Qr(/QwDY st 13.1V 71F HDOP00.7 SATS16
direwolf APRS Nov 3 01:27:47 aprs direwolf: [0.4] N8QH-9>APOT30,N8QH-9,N6ZX-3,WIDE2*:T#092,132,059,063,041,048,00000000
polaric APRS 03 nov 2015 01:27:48 [rf0] N8QH-9>APOT30,N8QH-9*,N6ZX-3*,WIDE2*:T#092,132,059,063,041,048,00000000
direwolf APRS Nov 3 01:32:10 aprs direwolf: [0.3] N8QH-9>APOT30,N8QH-9,N6ZX-3,WIDE2*:<0x0a>$ULTW00BD002202A300772763FFFF85A00001023D0131042900000080<0x0d>
```

polaric APRS 03 nov 2015 01:32:10 [rf0] N8QH-9>APOT30,N8QH-9_,N6ZX-3_,WIDE2*:

**Comment by ohanssen** [comment]
Hard to tell. The next version supports telemetry messages. Let me know if there are types of reports that are still not displayed on the map.

**Comment by elafargue** [comment]
Another example I noticed today (same sender). : N8QH-9 never appears on the map somehow...

14 jan 2016 00:06:36 [rf0] N8QH-9>APOT30,N6ZX-3*,WIDE1*,WIDE2-1:>S/V Ad Astra, Not Making Way, WDF2783@gmail.com
14 jan 2016 00:06:36 [rf0] N8QH-9>APOT30,N6ZX-3*,WIDE1*,WIDE2-1:/000632h/;Qr(/QwDY st 13.3V 66F HDOP00.9 SATS10 
14 jan 2016 00:06:37 [rf0] N8QH-9>APOT30,N6ZX-3*,WIDE1*,WIDE2-1:T#018,132,046,067,041,048,00000000
14 jan 2016 00:06:38 [rf0] N8QH-9>APOT30,N6ZX-3*,WIDE1*,BKELEY*,WIDE2*:>S/V Ad Astra, Not Making Way, WDF2783@gmail.com
14 jan 2016 00:06:38 [rf0] N8QH-9>APOT30,N6ZX-3*,WIDE1*,BKELEY*,WIDE2*:/000632h/;Qr(/QwDY st 13.3V 66F HDOP00.9 SATS10 
14 jan 2016 00:06:39 [rf0] N8QH-9>APOT30,N6ZX-3*,WIDE1*,BKELEY*,WIDE2*:T#018,132,046,067,041,048,00000000
14 jan 2016 00:06:43 [rf0] KI6TSF-8>APOTRS,N6ZX-3*,WIDE1*:T#9,023,023,048,011,000,00000000
