### ISSUE TITLE
Parsing issue ?

### ISSUE THREAD

**Issue by elafargue** [PolaricServer/aprsd#9]
The following packet is decoded by aprsd as "moving faster than 500km/h" ?

direwolf: [0.3] AE6LA-12>APU25N,N6ZX-3,WIDE1*,WIDE2-1:@062116z3756.87N/12200.49WR236/040/A=000181 Ken from Arnold {UIV32N}<0x0d>
direwolf: Position with time, REC. VEHICLE, UIview 32 bit apps
direwolf: N 37 56.8700, W 122 00.4900, 46 MPH, course 236, alt 181 ft
direwolf: Ken from Arnold {UIV32N}

polaric [rf0] AE6LA-12>APU25N,N6ZX-3_,WIDE1_,WIDE2-1:@062116z3756.87N/12200.49WR236/040/A=000181 Ken from Arnold {UIV32N}
polaric APRS **\* Moving faster than 500km/h. ignore.

**Comment by ohanssen** [comment]
I need to see the previous report to see where the error is.
